### PR TITLE
React functional component clarification

### PR DESCRIPTION
**Pull request by bogdanbacosca**

### CODE REVIEW

**Comment by rwieruch** [comment]
Hm, it applies to other component types like a React class component too, so I think the more generalized version holds true. What do you think?

**Comment by bogdanbacosca** [comment]
From what I understand, the sentence compares (states similarity) between class components and functional components?
So my thinking was that `concept of a class with declaration and instantiation` should compare `to a React functional component` insted of `React component` generally.

**Comment by rwieruch** [comment]
Ah no. The previous paragraph explains vanilla JavaScript classes, so the comparison is between a JavaScript class and a React component. Maybe it should be then "the concept of a JavaScript class".

**Comment by bogdanbacosca** [comment]
@rwieruch oh yes, that makes much more sense. I updated it with the reminder of 'JavaScript' class - someone else might confuse a JavaScript class with a "React class" just like I did, even though you were just talking about it moments before. I guess it can happen. 🙂

**Comment by rwieruch** [comment]
Perfect! Thank you @bogdanbacosca this is really helpful!

**Pull request merged**
